### ISSUE TITLE
Положение текстов 2 секвенции привести в соответствие с фигмой, Шрифт Gabarito medium 20

### ISSUE THREAD

**Issue by ghost** [ivanshum-mbf/thechangers#23]

**Comment by ghost** [comment]
@kingkastorsky Конкретней, типо чтобы первый текст был почти вверху, второй внизу? Третий по центру ставить не буду, он наезжает на космонавта тогда. В фигме и позы другие и космонафт другой.

**Comment by kingkastorsky** [comment]
Первый сверху
Второй снизу
Третий сверху и отцентрован 
После него появится 2000 speakers итд

**Comment by kingkastorsky** [comment]
И диапазон движения блоков текста должен быт минимальный, а не на пол высоты экрана, как сейчас

**Comment by ghost** [comment]
Принято!
